import { createHash } from 'node:crypto';
import { posix } from 'node:path';
import type { Kaos, StatResult } from '@moonshot-ai/kaos';
import { z } from 'zod';
import { sniffMediaFromMagic } from '../tools/support/file-type';
import type { AssetExecutionEnvelope } from './provider';
import { assetStagingRoot, isAssetStagingPath, validateAssetCandidateExecutionPolicy } from './safety';
import type { AssetArtifactManifest, AssetCandidateExecutionPolicy, AssetExecutionErrorCode, AssetExecutionIssue, AssetProviderOperation, VerifiedAssetExecutionResult } from './types';

const Sha256 = z.string().regex(/^[a-f0-9]{64}$/);
const Mime = z.string().regex(/^[a-z0-9][a-z0-9!#$&^_.+-]*\/[a-z0-9][a-z0-9!#$&^_.+-]*$/);
const Domain = z.string().trim().min(1).max(253);
export const AssetCandidateExecutionPolicySchema = z.object({
  candidateId: z.string().trim().min(1).max(128), operationKind: z.enum(['public_download', 'local_import', 'generation']),
  allowedDomains: z.array(Domain).max(32), allowedLicenses: z.array(z.string().trim().min(1).max(128)).min(1).max(32),
  maxTotalSizeBytes: z.number().int().positive().safe(), allowedExtensions: z.array(z.string().regex(/^[a-z0-9][a-z0-9+_-]{0,15}$/)).min(1).max(32),
  allowedMimeTypes: z.array(Mime).min(1).max(32),
  checksum: z.discriminatedUnion('mode', [z.object({ mode: z.literal('expected'), sha256: Sha256 }).strict(), z.object({ mode: z.literal('record_actual') }).strict()]),
}).strict();
const Money = z.object({ currency: z.string().trim().min(1).max(16), amount: z.number().finite().nonnegative() }).strict();
const Operation = z.object({
  id: z.string().trim().min(1).max(128), candidateId: z.string().trim().min(1).max(128), bomItemId: z.string().trim().min(1).max(128),
  kind: z.enum(['public_download', 'local_import', 'generation']), provider: z.string().trim().min(1).max(128),
  state: z.enum(['completed', 'failed', 'unavailable', 'cancelled']), stagingPath: z.string().trim().min(1).max(1024),
  finalSourceUrls: z.array(z.string().url().max(2048)).max(16).optional(), model: z.string().trim().min(1).max(256).optional(),
  promptRef: z.string().trim().min(1).max(1024).optional(), rawResponseRef: z.string().trim().min(1).max(1024).optional(),
  actualCost: Money.optional(), errorCode: z.string().trim().min(1).max(128).optional(), error: z.string().trim().min(1).max(4096).optional(),
}).strict();
const Artifact = z.object({
  id: z.string().trim().min(1).max(128), candidateId: z.string().trim().min(1).max(128), bomItemId: z.string().trim().min(1).max(128), stagingPath: z.string().trim().min(1).max(1024),
  sha256: Sha256, mimeType: Mime, sizeBytes: z.number().int().nonnegative().safe(),
  metadata: z.record(z.string().max(128), z.union([z.string().max(4096), z.number().finite(), z.boolean(), z.null()])), previewPaths: z.array(z.string().trim().min(1).max(1024)).max(8),
}).strict();
export const RawAssetWorkerManifestSchema = z.object({ schemaVersion: z.literal(1), runId: z.string().trim().min(1).max(128), confirmationHash: Sha256, operations: z.array(Operation).max(256), artifacts: z.array(Artifact).max(256) }).strict();
export type RawAssetWorkerManifest = z.infer<typeof RawAssetWorkerManifestSchema>;
export interface AssetRawWorkerAudit { readonly sha256: string; readonly byteLength: number; readonly redactedJson?: string; readonly truncated: boolean; }
export interface ParsedAssetWorkerResponse { readonly manifest: RawAssetWorkerManifest; readonly audit: AssetRawWorkerAudit; }
export interface AssetExecutionRuntime { readonly kaos: Pick<Kaos, 'stat' | 'readBytes' | 'iterdir' | 'mkdir'>; readonly cwd: string; }
export class AssetWorkerManifestParseError extends Error { constructor(readonly code: AssetExecutionErrorCode, message: string, readonly audit: AssetRawWorkerAudit) { super(message); this.name = 'AssetWorkerManifestParseError'; } }

const sensitive = new Set(['authorization','apikey','token','refreshtoken','accesstoken','idtoken','password','secret','clientsecret','apisecret','cookie','setcookie','bearer','privatekey']);
const secretPatterns = [/-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----[\s\S]*?-----END [^-]+ PRIVATE KEY-----/g, /\bAKIA[0-9A-Z]{16}\b/g, /\b(?:ghp|github_pat)_[A-Za-z0-9_]{20,}\b/g, /\bsk-[A-Za-z0-9_-]{20,}\b/g, /\bBearer\s+[A-Za-z0-9._~+/-]{16,}={0,2}\b/gi, /\b(?:api[_-]?key|access[_-]?token|refresh[_-]?token|id[_-]?token|token|password|secret)\s*[:=]\s*[^\s"'`]+/gi];
function redactString(value: string): string { let out = value; for (const pattern of secretPatterns) out = out.replace(pattern, '[REDACTED]'); return out; }
function redact(value: unknown, depth = 0): unknown { if (depth > 12) return '[REDACTED:depth]'; if (typeof value === 'string') return redactString(value); if (value === null || typeof value !== 'object') return value; if (Array.isArray(value)) return value.map((v) => redact(v, depth + 1)); const out: Record<string, unknown> = {}; for (const [key, v] of Object.entries(value as Record<string, unknown>)) out[key] = sensitive.has(key.toLowerCase().replaceAll(/[_\-.]/g, '')) ? '[REDACTED]' : redact(v, depth + 1); return out; }
function digest(value: string | Buffer): string { return createHash('sha256').update(value).digest('hex'); }
export function parseAssetWorkerManifest(rawResponse: string, options?: { readonly maxBytes?: number; readonly maxPersistedBytes?: number }): ParsedAssetWorkerResponse {
  const maxBytes = options?.maxBytes ?? 256 * 1024; const maxPersisted = options?.maxPersistedBytes ?? 64 * 1024; const byteLength = Buffer.byteLength(rawResponse); const base = { sha256: digest(rawResponse), byteLength, truncated: false };
  if (byteLength > maxBytes) throw new AssetWorkerManifestParseError('RESPONSE_TOO_LARGE', `Asset worker response exceeds ${String(maxBytes)} bytes.`, base);
  const text = rawResponse.trim(); if (!text.startsWith('{') || !text.endsWith('}')) throw new AssetWorkerManifestParseError('INVALID_JSON', 'Asset worker response must be one JSON object with no surrounding text.', base);
  let parsed: unknown; try { parsed = JSON.parse(text); } catch { throw new AssetWorkerManifestParseError('INVALID_JSON', 'Asset worker response is invalid JSON.', base); }
  const result = RawAssetWorkerManifestSchema.safeParse(parsed); if (!result.success) throw new AssetWorkerManifestParseError('SCHEMA_INVALID', 'Asset worker manifest failed strict schema validation.', base);
  let redactedJson = JSON.stringify(redact(result.data)); let truncated = false; if (Buffer.byteLength(redactedJson) > maxPersisted) { redactedJson = Buffer.from(redactedJson).subarray(0, maxPersisted).toString(); truncated = true; }
  return { manifest: result.data, audit: { ...base, redactedJson, truncated } };
}
const TYPE = 0o170000; const REG = 0o100000; const DIR = 0o040000; const LNK = 0o120000;
const kind = (s: StatResult) => s.stMode & TYPE; const isReg = (s: StatResult) => kind(s) === REG; const isDir = (s: StatResult) => kind(s) === DIR; const isLink = (s: StatResult) => kind(s) === LNK;
function abs(runtime: AssetExecutionRuntime, path: string): string { return posix.isAbsolute(path) ? path : posix.join(runtime.cwd.replaceAll('\\', '/'), path); }
function same(a: StatResult, b: StatResult): boolean { return a.stDev === b.stDev && a.stIno === b.stIno && a.stSize === b.stSize && a.stMtime === b.stMtime; }
function issue(code: AssetExecutionErrorCode, message: string, candidateId?: string, path?: string): AssetExecutionIssue { return { code, message, candidateId, path }; }
async function safeFile(runtime: AssetExecutionRuntime, path: string, issues: AssetExecutionIssue[], candidateId: string): Promise<{ bytes: Buffer; stat: StatResult } | undefined> {
  const parts = path.replaceAll('\\', '/').split('/').filter(Boolean); let cursor = ''; for (let i = 0; i < parts.length; i++) { cursor = cursor ? `${cursor}/${parts[i]!}` : parts[i]!; let st: StatResult; try { st = await runtime.kaos.stat(abs(runtime, cursor), { followSymlinks: false }); } catch { issues.push(issue('FILE_MISSING', `Missing path component ${cursor}.`, candidateId, path)); return; } if (isLink(st)) { issues.push(issue('SYMLINK_REJECTED', `Symlink path component ${cursor}.`, candidateId, path)); return; } if (i < parts.length - 1 && !isDir(st)) { issues.push(issue('NON_REGULAR_FILE', `Non-directory path component ${cursor}.`, candidateId, path)); return; } if (i === parts.length - 1 && (!isReg(st) || st.stNlink !== 1)) { issues.push(issue(!isReg(st) ? 'NON_REGULAR_FILE' : 'HARDLINK_REJECTED', `Artifact is not a unique regular file.`, candidateId, path)); return; } }
  const target = abs(runtime, path); let before: StatResult; let after: StatResult; let bytes: Buffer; try { before = await runtime.kaos.stat(target, { followSymlinks: false }); bytes = await runtime.kaos.readBytes(target); after = await runtime.kaos.stat(target, { followSymlinks: false }); } catch { issues.push(issue('FILE_MISSING', `Cannot read artifact ${path}.`, candidateId, path)); return; } if (!same(before, after) || isLink(after) || !isReg(after) || after.stNlink !== 1) { issues.push(issue('FILE_CHANGED_DURING_VERIFY', `Artifact changed during verification.`, candidateId, path)); return; } if (before.stSize !== bytes.byteLength) { issues.push(issue('SIZE_MISMATCH', `Stat size differs from bytes.`, candidateId, path)); return; } return { bytes, stat: after };
}
function mime(bytes: Buffer): string | undefined { const known = sniffMediaFromMagic(bytes)?.mimeType; if (known) return known; if (bytes.length >= 12 && bytes.subarray(0,4).toString() === 'RIFF' && bytes.subarray(8,12).toString() === 'WAVE') return 'audio/wav'; if (bytes.subarray(0,4).toString() === 'fLaC') return 'audio/flac'; if (bytes.subarray(0,4).toString() === 'OggS') return 'audio/ogg'; if (bytes.subarray(0,3).toString() === 'ID3' || (bytes[0] === 0xff && (bytes[1]! & 0xe0) === 0xe0)) return 'audio/mpeg'; if (bytes.subarray(0,4).toString() === 'glTF') return 'model/gltf-binary'; if (bytes.subarray(0,4).toString() === 'OTTO') return 'font/otf'; if (bytes.subarray(0,4).toString() === 'wOFF') return 'font/woff'; if (bytes.subarray(0,4).toString() === 'wOF2') return 'font/woff2'; if ((bytes[0] === 0 && bytes[1] === 1 && bytes[2] === 0 && bytes[3] === 0) || bytes.subarray(0,4).toString() === 'true') return 'font/ttf'; return; }
function ext(path: string): string { const base = posix.basename(path); const i = base.lastIndexOf('.'); return i > 0 ? base.slice(i + 1).toLowerCase() : ''; }
const extensionMimes: Readonly<Record<string, readonly string[]>> = { png: ['image/png'], jpg: ['image/jpeg'], jpeg: ['image/jpeg'], gif: ['image/gif'], webp: ['image/webp'], bmp: ['image/bmp'], tif: ['image/tiff'], tiff: ['image/tiff'], ico: ['image/x-icon'], mp4: ['video/mp4'], webm: ['video/webm'], mov: ['video/quicktime'], avi: ['video/x-msvideo'], mkv: ['video/x-matroska'], wav: ['audio/wav'], flac: ['audio/flac'], ogg: ['audio/ogg'], mp3: ['audio/mpeg'], glb: ['model/gltf-binary'], ttf: ['font/ttf'], otf: ['font/otf'], woff: ['font/woff'], woff2: ['font/woff2'] };
function extensionMatchesMime(path: string, actualMime: string): boolean { return extensionMimes[ext(path)]?.includes(actualMime) === true; }
function allowedUrl(value: string, domains: readonly string[]): boolean { try { const u = new URL(value); return !u.username && !u.password && (u.protocol === 'http:' || u.protocol === 'https:') && domains.map((d) => d.replace(/\.$/, '').toLowerCase()).includes(u.hostname.replace(/\.$/, '').toLowerCase()); } catch { return false; } }
export async function ensureCleanAssetStagingRoot(runtime: AssetExecutionRuntime, runId: string): Promise<void> { const root = abs(runtime, assetStagingRoot(runId)); try { const st = await runtime.kaos.stat(root, { followSymlinks: false }); if (isLink(st) || !isDir(st)) throw new Error('Asset staging root is not a directory.'); for await (const _ of runtime.kaos.iterdir(root)) throw new Error('Asset staging root is not empty.'); } catch (error) { if (error instanceof Error && /not a directory|not empty/i.test(error.message)) throw error; await runtime.kaos.mkdir(root, { parents: true, existOk: true }); } }
async function files(runtime: AssetExecutionRuntime, root: string, issues: AssetExecutionIssue[]): Promise<string[]> { const out: string[] = []; const walk = async (dir: string): Promise<void> => { for await (const entry of runtime.kaos.iterdir(dir)) { const st = await runtime.kaos.stat(entry, { followSymlinks: false }); if (isLink(st)) { issues.push(issue('SYMLINK_REJECTED', 'Staging contains symlink.', undefined, entry)); return; } if (isDir(st)) await walk(entry); else if (isReg(st)) out.push(entry.replaceAll('\\', '/')); else issues.push(issue('NON_REGULAR_FILE', 'Staging contains non-regular entry.', undefined, entry)); } }; try { await walk(abs(runtime, root)); } catch { issues.push(issue('FILE_MISSING', 'Cannot list staging root.', undefined, root)); } return out; }

export async function verifyAssetWorkerManifest(input: { readonly manifest: RawAssetWorkerManifest; readonly envelope: AssetExecutionEnvelope; readonly policies: readonly AssetCandidateExecutionPolicy[]; readonly confirmationHash: string; readonly runtime: AssetExecutionRuntime; readonly signal?: AbortSignal }): Promise<VerifiedAssetExecutionResult> {
  const issues: AssetExecutionIssue[] = []; const confirmed = input.envelope.confirmation.candidateIds; const items = new Map(input.envelope.items.map((x) => [x.candidate.id, x])); const policies = new Map(input.policies.map((x) => [x.candidateId, x])); const fail = (ops: AssetProviderOperation[] = [], arts: AssetArtifactManifest[] = [], status: VerifiedAssetExecutionResult['status'] = 'failed'): VerifiedAssetExecutionResult => ({ runId: input.envelope.runId, confirmationHash: input.confirmationHash, status, operations: ops, artifacts: arts, issues, counts: { confirmed: confirmed.length, completed: ops.filter((x) => x.state === 'completed').length, unavailable: ops.filter((x) => x.state === 'unavailable').length, failed: ops.filter((x) => x.state === 'failed' || x.state === 'cancelled').length, artifacts: arts.length }, cost: { currency: input.envelope.confirmation.costLimit?.currency ?? 'UNKNOWN', limit: input.envelope.confirmation.costLimit?.max ?? 0, reported: 0, fullyVerified: false } });
  if (input.manifest.runId !== input.envelope.runId || input.manifest.confirmationHash !== input.confirmationHash) { issues.push(issue('CONFIRMATION_MISMATCH', 'Worker manifest does not match approved envelope.')); return fail(); }
  if (input.manifest.operations.length !== confirmed.length) { issues.push(issue('UNEXPECTED_CANDIDATE', 'Operation set differs from confirmed candidate set.')); return fail(); }
  const opIds = new Set<string>(); const opCandidates = new Set<string>(); const artIds = new Set<string>(); const artCandidates = new Set<string>(); const opBy = new Map<string, RawAssetWorkerManifest['operations'][number]>(); const artBy = new Map<string, RawAssetWorkerManifest['artifacts'][number]>();
  for (const op of input.manifest.operations) { if (opIds.has(op.id) || opCandidates.has(op.candidateId)) issues.push(issue('DUPLICATE_ID', 'Duplicate operation id or candidate.', op.candidateId)); opIds.add(op.id); opCandidates.add(op.candidateId); opBy.set(op.candidateId, op); }
  for (const art of input.manifest.artifacts) { if (artIds.has(art.id) || artCandidates.has(art.candidateId)) issues.push(issue('DUPLICATE_ID', 'Duplicate artifact id or candidate.', art.candidateId)); artIds.add(art.id); artCandidates.add(art.candidateId); artBy.set(art.candidateId, art); }
  for (const id of confirmed) if (!opCandidates.has(id)) issues.push(issue('UNEXPECTED_CANDIDATE', 'Missing confirmed candidate operation.', id)); for (const id of opCandidates) if (!confirmed.includes(id)) issues.push(issue('UNEXPECTED_CANDIDATE', 'Unconfirmed candidate operation.', id)); if (issues.length) return fail();
  const operations: AssetProviderOperation[] = []; const artifacts: AssetArtifactManifest[] = []; const manifested = new Set<string>(); let reported = 0; let fullyVerified = true;
  for (const id of confirmed) { input.signal?.throwIfAborted(); const item = items.get(id)!; const policy = policies.get(id) ?? item.policy; const op = opBy.get(id)!; const art = artBy.get(id); const policyIssues = validateAssetCandidateExecutionPolicy(item.candidate, policy); if (policyIssues.length) { issues.push(...policyIssues); return fail(); } if (op.bomItemId !== item.bomItem.id || op.kind !== policy.operationKind || op.stagingPath !== item.stagingPath || op.provider !== item.candidate.provider) { issues.push(issue('PATH_MISMATCH', 'Worker operation differs from approved envelope.', id, op.stagingPath)); return fail(); }
    if (op.state !== 'completed') { if (art) { issues.push(issue('SCHEMA_INVALID', 'Unavailable/failed operation has an artifact.', id)); return fail(); } if (op.actualCost) { if (op.actualCost.currency !== (input.envelope.confirmation.costLimit?.currency ?? '')) { issues.push(issue('COST_CURRENCY_MISMATCH', 'Cost currency mismatch.', id)); return fail(); } reported += op.actualCost.amount; } operations.push({ id: op.id, kind: policy.operationKind, provider: item.candidate.provider, candidateId: id, bomItemId: item.bomItem.id, state: op.state, stagingPath: item.stagingPath, model: op.model, promptRef: op.promptRef, rawResponseRef: op.rawResponseRef, error: op.error, actualCost: op.actualCost, finalSourceUrls: op.finalSourceUrls }); continue; }
    if (!art) { issues.push(issue('QUANTITY_EXCEEDED', 'Completed operation must have one artifact.', id)); return fail(); } if (policy.operationKind === 'generation' && !op.promptRef) { issues.push(issue('SCHEMA_INVALID', 'Generation requires promptRef.', id)); return fail(); } if (item.candidate.estimatedCost?.amount && item.candidate.estimatedCost.amount > 0) { fullyVerified = false; operations.push({ id: op.id, kind: policy.operationKind, provider: item.candidate.provider, candidateId: id, bomItemId: item.bomItem.id, state: 'unavailable', stagingPath: item.stagingPath, error: 'Paid provider has no trusted billing attestation.' }); continue; }
    if (!isAssetStagingPath(input.envelope.runId, art.stagingPath) || art.stagingPath !== item.stagingPath) { issues.push(issue('PATH_MISMATCH', 'Artifact path is not the exact envelope path.', id, art.stagingPath)); return fail(); } if (policy.operationKind === 'public_download' && (!item.candidate.sourceUrl || !allowedUrl(item.candidate.sourceUrl, policy.allowedDomains) || (op.finalSourceUrls ?? []).some((u) => !allowedUrl(u, policy.allowedDomains)))) { issues.push(issue('DOMAIN_DENIED', 'Source or final URL is outside exact domain allowlist.', id)); return fail(); }
    const primary = await safeFile(input.runtime, art.stagingPath, issues, id); if (!primary) return fail(); let total = primary.bytes.byteLength; manifested.add(art.stagingPath); const previews: string[] = []; for (const p of art.previewPaths) { if (!isAssetStagingPath(input.envelope.runId, p)) { issues.push(issue('PATH_ESCAPE', 'Preview escapes staging.', id, p)); return fail(); } const v = await safeFile(input.runtime, p, issues, id); if (!v) return fail(); total += v.bytes.byteLength; previews.push(p); manifested.add(p); }
    const actualSha = digest(primary.bytes); const actualMime = mime(primary.bytes); const extension = ext(art.stagingPath); if (total > policy.maxTotalSizeBytes) issues.push(issue('SIZE_EXCEEDED', 'Candidate exceeds maximum total size.', id)); if (!policy.allowedExtensions.includes(extension)) issues.push(issue('EXTENSION_DENIED', 'Extension denied by policy.', id, art.stagingPath)); if (!actualMime) issues.push(issue('MIME_UNVERIFIED', 'MIME cannot be verified from magic bytes.', id, art.stagingPath)); else if (!policy.allowedMimeTypes.includes(actualMime) || !extensionMatchesMime(art.stagingPath, actualMime)) issues.push(issue('MIME_MISMATCH', 'MIME denied or does not match extension.', id, art.stagingPath)); if (art.sha256 !== actualSha) issues.push(issue('CHECKSUM_MISMATCH', 'Worker checksum differs from measured bytes.', id, art.stagingPath)); if (art.sizeBytes !== primary.bytes.byteLength) issues.push(issue('SIZE_MISMATCH', 'Worker size differs from measured bytes.', id, art.stagingPath)); if (art.mimeType !== actualMime) issues.push(issue('MIME_MISMATCH', 'Worker MIME differs from measured bytes.', id, art.stagingPath)); if (policy.checksum.mode === 'expected' && policy.checksum.sha256 !== actualSha) issues.push(issue('CHECKSUM_MISMATCH', 'Measured checksum differs from expected policy.', id, art.stagingPath)); if (issues.length) return fail();
    operations.push({ id: op.id, kind: policy.operationKind, provider: item.candidate.provider, candidateId: id, bomItemId: item.bomItem.id, state: 'completed', stagingPath: item.stagingPath, model: op.model, promptRef: op.promptRef, rawResponseRef: op.rawResponseRef, actualCost: op.actualCost, finalSourceUrls: op.finalSourceUrls }); if (op.actualCost) { if (op.actualCost.currency !== input.envelope.confirmation.costLimit?.currency) { issues.push(issue('COST_CURRENCY_MISMATCH', 'Cost currency mismatch.', id)); return fail(); } reported += op.actualCost.amount; } artifacts.push({ id: art.id, candidateId: id, bomItemId: item.bomItem.id, stagingPath: item.stagingPath, sha256: actualSha, mimeType: actualMime!, sizeBytes: primary.bytes.byteLength, metadata: redact(art.metadata) as AssetArtifactManifest['metadata'], previewPaths: previews, provider: item.candidate.provider, model: op.model, promptRef: op.promptRef, provenance: item.candidate.provenance }); }
  const listed = await files(input.runtime, assetStagingRoot(input.envelope.runId), issues); for (const path of listed) { const relative = path.startsWith(input.runtime.cwd.replaceAll('\\', '/') + '/') ? path.slice(input.runtime.cwd.replaceAll('\\', '/').length + 1) : path; if (!manifested.has(relative)) issues.push(issue('UNMANIFESTED_FILE', 'Unmanifested staging file.', undefined, relative)); } if (issues.length) return fail(); if (input.envelope.confirmation.costLimit && reported > input.envelope.confirmation.costLimit.max) { issues.push(issue('COST_EXCEEDED', 'Actual cost exceeds approved limit.')); return fail(); }
  const completed = operations.filter((x) => x.state === 'completed').length; const unavailable = operations.filter((x) => x.state === 'unavailable').length; const status: VerifiedAssetExecutionResult['status'] = completed === confirmed.length ? 'completed' : completed > 0 && unavailable + completed === confirmed.length ? 'partial' : unavailable === confirmed.length ? 'unavailable' : 'failed'; if (status === 'failed') return fail(operations, []); return { runId: input.envelope.runId, confirmationHash: input.confirmationHash, status, operations, artifacts, issues, counts: { confirmed: confirmed.length, completed, unavailable, failed: 0, artifacts: artifacts.length }, cost: { currency: input.envelope.confirmation.costLimit?.currency ?? 'UNKNOWN', limit: input.envelope.confirmation.costLimit?.max ?? 0, reported, fullyVerified: fullyVerified && status === 'completed' } };
}
